#!/usr/bin/env bash
# The script configures a new Ubuntu machine to install Nginx.

# Update system repo
apt update

# Install Nginx
apt install nginx -y

# Open port 80 for listening
ufw allow 'Nginx HTTP'

# HTML constains string
echo 'Hello World!' > /var/www/html/index.html

# Restart Nginx
service nginx restart
