#!/usr/bin/env bash
# This script configures an ubuntu machine by adding a custom HTTP header to the server.
# Update system repo
apt update

# Install Nginx
apt install nginx -y

# Open port 80 for listening
ufw allow 'Nginx HTTP'

# Index html constains string
echo 'Hello World!' > /var/www/html/index.html

# Error html contains error message
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure server
SERVER_CONFIG="\
		server	{
				listen 80 default_server;
				listen [::]:80 default_server;
				error_page 404 /404.html;
				root /var/www/html;
				index index.html index.htm index.nginx-debian.html;
				server_name _;
				location / {
							add_header X-Served-By \$hostname;
							try_files \$uri \$uri/ =404;
				}
				rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
		}"

# Place configuration in nginx file
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Restart Nginx
service nginx restart
