#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.

passwd=$1

# Connect to MySQL database and dump databases
sudo mysqldump -u root -p"$passwd" --all-databases | sudo tee backup.sql > /dev/null

# Get file date
date=$(date +'%d-%m-%Y')

#Get filename
filename="$date.tar.gz"

# Compress backup
sudo tar -czf "$filename" backup.sql
