#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument


# If no arguments passed
if [[ $# -ne 1 ]]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

else
	arg="$1"
	ping -c 5 "$arg"
fi
