#!/usr/bin/env bash
# A Bash script that creates the file /var/run/myscript.pid containing its PID and displays:
# "To infinity and beyond" indefinitely
# "I hate the kill command" when receiving a SIGTERM signal
# "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Store script's PID
echo $$ > "/var/run/myscript.pid"

# trap call to catch SIGQUIT or SIGTERM signal
trap "rm '/var/run/myscript.pid'; exit" SIGQUIT SIGTERM

# trap call to catch SIGTERM signal
trap "echo 'I hate the kill command'; exit" SIGTERM

# trap call to catch SIGINT signal
trap "echo 'Y U no love me?!'" SIGINT

while true; do
	text="To infinity and beyond"
	echo "$text"
	sleep 2
done
