#!/usr/bin/env bash
# A Bash (init) script that manages manage_my_process

# Start argument
start() {
	./manage_my_process &
	echo $$ > "/var/run/my_process.pid"
	echo "manage_my_process started"
}

# Stop argument
stop() {
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

# Restart argument
restart() {
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > "/var/run/my_process.pid"
	echo "manage_my_process restarted"
}

# Handle command line argument
case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
