#!/usr/bin/env bash
# A Bash script that displays:
# "To infinity and beyond" indefinitely
# a "sleep 2" in between each iteration
# "I am invincible!!!" when receiving a SIGTERM signal

# trap call to catch SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
	text="To infinity and beyond"
	echo "$text"
	sleep 2
done
