#!/usr/bin/env bash
# This script is displays:
# "FizzBuzz" when the number is a multiple of 3 and 5
# "Fizz" when the number is multiple of 3
# "Buzz" when the number is a multiple of 5

i=1
while [[ $i -le 100 ]]; do
	# number is a multiple of 3 and 5
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"

	# number is a multiple of 3
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"

	# number is a multiple of 5
	elif (( i % 5 == 0 ))
	then
		echo "Buzz";

	# number is not a multiple of 3, 5 or 15
	else
		echo "$i"
	fi
	((i++))
done
