#!/usr/bin/env bash
# This script is displays:
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iterations

i=1
while [[ $i -le 10 ]]; do
	# for the 4th iteration display "bad luck"
	if [[ $i -eq 4 ]]
	then
		echo "bad luck"

	# for the 8th iteration display "good luck"
	elif [[ $i -eq 8 ]]
	then
		echo "good luck"

	# for other iterations
	else
		echo "Best School";
	fi
	((i++))
done
