#!/usr/bin/env bash
# This script is displays:
# hours from 0 to 12
# minutes from 1 to 59

i=0
# i will point to hours
while [[ $i -le 12 ]]; do
	echo "Hour: $i"
	j=1
	# j will point to minutes
	while [[ $j -le 59 ]]; do
		echo "$j"
		((j++))
	done
	((i++))
done
