#!/usr/bin/env bash
# This script is displays:
# the content of the current directory in a list format

# variable points to current directory
current_dir=$(pwd)

# iterate through the files in the current directory
for file in $current_dir/*; do
	# Use cut to extract the part of the file name after the first dash
	# The field column for the files is column 5
	echo "$file" | cut -d "-" -f5
done
