#!/usr/bin/env bash
# This script gives information about the school file

file_name="school"

# Check if file exists
if [[ -e "$file_name" ]]
then
	echo "school file exists"
	
	# Check if file is empty
	if [[ -s "$file_name" ]]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# Check if file is a regular file
	if [[ -f "$file_name" ]]
	then
		echo "school is a regular file"
	fi

# File does not exist
else
	echo "school file does not exist"
fi
	
