#!/usr/bin/env bash
# This script installs ufw and setups a few rules.

# Update repo
apt update

# Install ufw
apt install -y ufw

# Allow ports
ufw allow 22
ufw allow 80
ufw allow 443

# Enable firewall
ufw enable
