#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements

# Add localhost to hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new

# Add facebook to hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

# Copy ~/hosts.new to /etc/hosts
cp -f ~/hosts.new /etc/hosts
