#!/usr/bin/env bash
# This script runs Nginx as the user nginx

# Change user
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

# Listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Adjust file mode
chmod 644 /etc/nginx/nginx.conf

# Kill apache listening on 8080
pkill apache2

# Restart nginx as nginx user
sudo -u nginx service nginx restart
