#!/usr/bin/env bash
# This script runs Nginx as the user nginx

# Add nginx
useradd nginx

# Change user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
