#!/usr/bin/env bash
# This script tells the master Gunicorn renew all the workers gracefully

# Search for Gunicorn process by name
pid=$(pgrep -f gunicorn)

# Use HUP option with kill to initiate graceful reload
kill -HUP "$pid"

# Restart ginicorn
gunicorn --bind :5003 --workers 3 web_dynamic.2-hbnb:app
